### ISSUE TITLE
What about without JSON?

### ISSUE THREAD

**Issue by batjko** [dotchev/rest-bench#1]
Have you tried this without making go parse JSON, but use some operation with a scalar type like string?

I don't know anything about Go, but given Javascript's advantage with everything being JSON natively, I wonder how much of a difference it makes.

You could use some long lorem ipsum string or just the word "hello" repeated 100 times, and have the server count the occurrences of the word as a result of the request.

**Comment by udhos** [comment]
I suppose javascript native support for JSON is actually written in C.
Golang default JSON package isn't the fastest.
So, this benchmark may be comparing C-JSON against slow-Go-JSON.
I think a faster JSON package for Go should be used as well.

**Comment by dotchev** [comment]
My observation is that most REST APIs use JSON.
Also the goal here is to compare what comes out of the box as this is what most projects actually use.
