### ISSUE TITLE
Go response body

### ISSUE THREAD

**Issue by anjmao** [dotchev/rest-bench#2]
Hi, thanks for comparison, I'm amazed that Go is slower on such test since really expected Go to win here. Here https://github.com/dotchev/rest-bench/blob/master/server.go#L22 it is good practice to close request body to prevent possible leaks.
```go
defer r.Body.Close()
```

BTW I made similar go vs .net core comparison https://github.com/anjmao/netcore-vs-golang where go was faster.

**Comment by dotchev** [comment]
```golang
        // The Server will close the request body. The ServeHTTP
        // Handler does not need to.
        Body io.ReadCloser
```
https://golang.org/pkg/net/http/#Request
