### ISSUE TITLE
Setting MAXPROCS to 1 makes this totally unfair.

### ISSUE THREAD

**Issue by TheSalarKhan** [dotchev/rest-bench#3]
I read the documentation in the README file, we have set MAXPROCS to 1 for Go, and there are no such restrictions for JS because of the premise that all the JavaScript (The runtime) executes on a single thread. Well that premise is not entirely correct, because even though the JS thread is a single thread, the JS runtime does not have a single thread, it launches system threads for every async opertion that needs to be done. Let me explain.

When we do anything async in JS like setInterval or an API call, the JS runtime does a call to the V8 engine and the v8 engine launches a system thread to handle that task asynchronusly, and when the task completes the v8 engine adds a job - eg: the callback passed to then() - which is then executed on the main JS thread. So the JS runtime launches more than one system thread to get the job done.

However when we restrict GO to only one processor, we are telling it that it can only ever use one system thread. Which means that we strictly keep Go to only one system thread, so even if it wants to create a new thread to not block other operations it won't be able to do that.
Read here for a reference: https://dave.cheney.net/tag/gomaxprocs

Let me explain this more elaborately. With GOMAXPROCS set to 1 when we do a blocking call on the main Go thread - for example: when we are reading the request body from an http client connection - the Go runtime cannot create more system threads to move the http accept goroutine to another thread so that it can accept more connections.

Whereas in contrast the node runtime is accepting connections on the main thread and all the request processing and parsing is happening on other System threads created by the V8 runtime.

When we say that Nodejs is single threaded we don't mean that it only uses a single system thread, what is meant is that the main JS thread never gets blocked because of operations like network calls and sleep syscalls, as the v8 runtime schedules these async operations on a different system thread. Go achieves the exact same thing by a different mechanism in which if an async operation is called on a thread then it moves all the other operations to a new thread in order to not block the execution of those operations. Therefore I think that by setting MAXPROCS to 1 we disable the very mechanism that makes Go what it is.

A true test of the two would be if we set no flags or anything, and we ran the tests inside a VM to which we only allocated a single CPU, and no restrictions on the number of System threads that the runtimes can create.

This is just a critique on the methodology used for this test. I am not vouching for any one of the two, only a fair test will tell. Only in God we believe, everything else we test.

**Comment by dotchev** [comment]
Thank you for the feedback.

Here is what the [official doc](https://golang.org/pkg/runtime/) says about GOMAXPROCS:

> The GOMAXPROCS variable limits the number of operating system threads that can execute user-level Go code simultaneously. There is no limit to the number of threads that can be blocked in system calls on behalf of Go code; those do not count against the GOMAXPROCS limit.

Since many people commented that limiting GOMAXPROCS is unfair to Go, I have tested also without any flags, providing the processes with equal resources. See [Single core, unlimited threads](https://github.com/dotchev/rest-bench/blob/master/README.md#single-core-unlimited-threads) and [All CPU cores, no limits](https://github.com/dotchev/rest-bench/blob/master/README.md#all-cpu-cores-no-limits).

**Comment by TheSalarKhan** [comment]
Thank you @dotchev This is really cool I missed this part out entirely.
```
There is no limit to the number of threads that can be blocked in system calls on behalf of Go code; those do not count against the GOMAXPROCS limit.
```

So yep, its seems like a pretty fair comparison now. :+1:
